function ExportGeometryLatex(GeometryStatistics,filename)
%*******************************************************************************
% EXPORTGEOMETRYLATEX
%
% Purpose:
%   Exports the archaeological geometry statistics to a LaTeX table using
%   the booktabs package.
%
% Inputs:
%   GeometryStatistics : table created by ComputeGeometryStatistics
%   filename           : output .tex file (optional)
%
% Example:
%
%   ExportGeometryLatex(GeometryStatistics)
%
%   ExportGeometryLatex(GeometryStatistics,'GeometryStatistics.tex')
%
% Authors:
%   GPINV Research Group
%   University of Oviedo
%
% Copyright (c) 2026 GPINV Research Group, University of Oviedo
%*******************************************************************************

if nargin<2
    filename='GeometryStatistics.tex';
end

fid=fopen(filename,'w');

if fid==-1
    error('Unable to create %s.',filename);
end

fprintf(fid,'%% Automatically generated by ExportGeometryLatex.m\n');
fprintf(fid,'%% Requires: \\usepackage{booktabs}\n\n');

fprintf(fid,'\\begin{table}[ht]\n');
fprintf(fid,'\\centering\n');
fprintf(fid,'\\caption{Descriptive statistics of the recovered archaeological bodies.}\n');
fprintf(fid,'\\label{tab:GeometryStatistics}\n');
fprintf(fid,'\\begin{tabular}{llrrrrrrr}\n');

fprintf(fid,'\\toprule\n');

fprintf(fid,...
'Body & Parameter & Mean & Median & Std & CV (\\%%) & IQR & Min & Max\\\\\n');

fprintf(fid,'\\midrule\n');

for i=1:height(GeometryStatistics)

    fprintf(fid,...
'%s & %s & %.2f & %.2f & %.2f & %.2f & %.2f & %.2f & %.2f\\\\\n',...
GeometryStatistics.Body{i},...
GeometryStatistics.Parameter{i},...
GeometryStatistics.Mean(i),...
GeometryStatistics.Median(i),...
GeometryStatistics.Std(i),...
GeometryStatistics.CV(i),...
GeometryStatistics.IQR(i),...
GeometryStatistics.Minimum(i),...
GeometryStatistics.Maximum(i));

end

fprintf(fid,'\\bottomrule\n');
fprintf(fid,'\\end{tabular}\n');
fprintf(fid,'\\end{table}\n');

fclose(fid);

fprintf('LaTeX table exported to %s\n',filename);

end